Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -58,11 +58,26 @@ jobs:
         echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
         echo "$PWD/android-sdk/tools/bin" >> $GITHUB_PATH
 
+    - name: Check SDK directory
+      run: |
+        ls -R $ANDROID_HOME
+
     - name: Install SDK components and accept licenses
       run: |
-        $ANDROID_HOME/tools/bin/sdkmanager --update
-        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
-        $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "build-tools;28.0.3" "platforms;android-25"
+        echo "Checking for sdkmanager in different locations"
+        if [ -f "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
+          SDKMANAGER="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
+        elif [ -f "$ANDROID_HOME/tools/bin/sdkmanager" ]; then
+          SDKMANAGER="$ANDROID_HOME/tools/bin/sdkmanager"
+        else
+          echo "sdkmanager not found"
+          exit 1
+        fi
+        echo "Using sdkmanager at $SDKMANAGER"
+        
+        $SDKMANAGER --update
+        yes | $SDKMANAGER --licenses
+        $SDKMANAGER "platform-tools" "build-tools;28.0.3" "platforms;android-25"
       
     - name: Configure environment
       run: |
